services:
- type: web
  name: tammyhartlinescapstone
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -b 0.0.0.0:8050 app:app
  repo: https://github.com/tjhartline/capstone
  branch: master
  runtime: python
  ipAllowList: 
    # Render ip's
    -source: 35.160.120.126
    -source: 44.233.151.27
    -source: 34.211.200.85
    # Allow external
    source: 0.0.0.0/0
databases:
- name: SQLite
  databaseName: animals
  user: aacuser
  password: securepassword

